import { useCallback, useEffect, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Link } from 'react-router-dom'
import { getDigests, extractSlackSection } from '@/api/digests'
import type { Digest } from '@/types/digest'

const AI_DISCLAIMER = 'This digest was generated by AI and should be verified for accuracy before sharing.'

function formatPeriodRange(periodStart: string, periodEnd: string): string {
  const s = new Date(periodStart).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
  const e = new Date(periodEnd).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })
  return `Week of ${s} – ${e}`
}

function MdLink({ href, children }: { href?: string; children?: React.ReactNode }) {
  if (href?.startsWith('/')) {
    return <Link to={href}>{children}</Link>
  }
  return (
    <a href={href} target="_blank" rel="noopener noreferrer">
      {children}
    </a>
  )
}

export function DigestPage() {
  const [published, setPublished] = useState<Digest[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const p = await getDigests()
      setPublished(p ?? [])
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load digests')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    load()
  }, [load])

  const handleCopySlack = useCallback((contentMd: string) => {
    const slack = extractSlackSection(contentMd)
    if (slack) {
      navigator.clipboard.writeText(slack)
    }
  }, [])

  if (loading) {
    return (
      <div className="mx-auto max-w-3xl">
        <p className="text-sm text-zinc-500 dark:text-zinc-400">Loading…</p>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <h1 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">
        Weekly digest
      </h1>
      <p className="text-sm text-zinc-600 dark:text-zinc-400">
        A weekly digest is generated automatically from recent design work with AI. Be sure to double check information as AI doesn&apos;t always get it right.
      </p>

      {error && (
        <div
          className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/50 dark:text-red-200"
          role="alert"
        >
          {error}
        </div>
      )}

      {/* Feed of published digests */}
      {published.length === 0 ? (
        <div className="rounded-lg border border-dashed border-zinc-300 bg-zinc-50/50 py-12 dark:border-zinc-600 dark:bg-zinc-800/50">
          <p className="text-center text-sm text-zinc-600 dark:text-zinc-400">
            No digests yet. Weekly digests are published automatically once the system is connected.
          </p>
        </div>
      ) : (
        <div className="space-y-8">
          {published.map((digest) => (
            <article
              key={digest.id}
              className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"
            >
              <header className="mb-4">
                <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50">
                  {formatPeriodRange(digest.periodStart, digest.periodEnd)}
                </h2>
                <p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                  Published {new Date(digest.publishedAt).toLocaleDateString(undefined, { dateStyle: 'medium' })}
                </p>
              </header>
              <div className="prose prose-sm max-w-none dark:prose-invert description-view">
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{ a: ({ href, children }) => <MdLink href={href}>{children}</MdLink> }}
                >
                  {digest.contentMd}
                </ReactMarkdown>
              </div>
              <p className="mt-4 border-t border-zinc-200 pt-4 text-xs italic text-zinc-500 dark:border-zinc-700 dark:text-zinc-400">
                {AI_DISCLAIMER}
              </p>
              <div className="mt-3">
                <button
                  type="button"
                  onClick={() => handleCopySlack(digest.contentMd)}
                  className="rounded-md border border-zinc-300 bg-white px-3 py-1.5 text-sm font-medium text-zinc-700 hover:bg-zinc-50 dark:border-zinc-600 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700"
                >
                  Copy for Slack
                </button>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  )
}
