import { useCallback, useEffect, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { useAuth } from '@/hooks/useAuth'
import { isAdmin } from '@/lib/admin'
import {
  getDraftDigest,
  publishDigest,
  generateDigest,
  regenerateDigest,
} from '@/api/digests'
import type { DraftDigest } from '@/types/digest'

function formatPeriod(periodEnd: string): string {
  const d = new Date(periodEnd)
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })
}

export function SettingsPage() {
  const { user } = useAuth()
  const admin = isAdmin(user?.id)
  const [draft, setDraft] = useState<DraftDigest | null>(null)
  const [loading, setLoading] = useState(false)
  const [publishing, setPublishing] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [regenerating, setRegenerating] = useState(false)
  const [digestError, setDigestError] = useState<string | null>(null)

  const loadDraft = useCallback(async () => {
    if (!admin) return
    setLoading(true)
    setDigestError(null)
    try {
      const d = await getDraftDigest()
      setDraft(d ?? null)
    } catch (e) {
      setDigestError(e instanceof Error ? e.message : 'Failed to load draft')
    } finally {
      setLoading(false)
    }
  }, [admin])

  useEffect(() => {
    loadDraft()
  }, [loadDraft])

  const handlePublish = async () => {
    if (!draft) return
    setPublishing(true)
    setDigestError(null)
    try {
      await publishDigest({ draftId: draft.id })
      await loadDraft()
    } catch (e) {
      setDigestError(e instanceof Error ? e.message : 'Failed to publish')
    } finally {
      setPublishing(false)
    }
  }

  const handleGenerate = async () => {
    setGenerating(true)
    setDigestError(null)
    try {
      await generateDigest()
      await loadDraft()
    } catch (e) {
      setDigestError(e instanceof Error ? e.message : 'Failed to generate draft')
    } finally {
      setGenerating(false)
    }
  }

  const handleRegenerate = async () => {
    setRegenerating(true)
    setDigestError(null)
    try {
      await regenerateDigest()
      await loadDraft()
    } catch (e) {
      setDigestError(e instanceof Error ? e.message : 'Failed to regenerate')
    } finally {
      setRegenerating(false)
    }
  }

  return (
    <div className="mx-auto max-w-2xl space-y-8">
      <div>
        <h1 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">
          Settings
        </h1>
        <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
          Configure digest and app behavior. Admin-only options are shown when you have admin access.
        </p>
      </div>

      <section className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
        <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-50">
          Weekly digest
        </h2>
        <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
          The weekly digest is generated automatically by AI from recent public drops. Once your deployment is connected to a weekly cron (e.g. Vercel Cron or a scheduler), a new digest will be created and published each week. Digests tag relevant people, use bullet points, quotes, and links, and always include a note that the content was generated by AI and should be verified for accuracy.
        </p>
      </section>

      {admin && (
        <section className="rounded-lg border border-zinc-200 bg-zinc-50/50 p-6 dark:border-zinc-700 dark:bg-zinc-800/50">
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-50">
            Admin: digest draft &amp; publish
          </h2>
          <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
            Generate a draft from the last 7 days of public drops, review it, then publish to the Digest feed.
          </p>
          {digestError && (
            <div className="mt-3 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/50 dark:text-red-200">
              {digestError}
            </div>
          )}
          {loading ? (
            <p className="mt-4 text-sm text-zinc-500 dark:text-zinc-400">Loading draft…</p>
          ) : draft ? (
            <div className="mt-4 space-y-4">
              <p className="text-sm text-zinc-600 dark:text-zinc-400">
                Period: {formatPeriod(draft.periodStart)} – {formatPeriod(draft.periodEnd)}
              </p>
              <div className="rounded border border-zinc-200 bg-white p-4 dark:border-zinc-700 dark:bg-zinc-900">
                <div className="prose prose-sm max-w-none dark:prose-invert description-view">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{draft.contentMd}</ReactMarkdown>
                </div>
              </div>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={handlePublish}
                  disabled={publishing}
                  className="rounded-md bg-zinc-900 px-4 py-2 text-sm font-medium text-white hover:bg-zinc-800 disabled:opacity-50 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-200"
                >
                  {publishing ? 'Publishing…' : 'Publish digest'}
                </button>
                <button
                  type="button"
                  onClick={handleRegenerate}
                  disabled={regenerating}
                  className="rounded-md border border-zinc-300 bg-white px-4 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-50 dark:border-zinc-600 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700"
                >
                  {regenerating ? 'Regenerating…' : 'Regenerate'}
                </button>
              </div>
            </div>
          ) : (
            <div className="mt-4 space-y-2">
              <p className="text-sm text-zinc-600 dark:text-zinc-400">
                No draft yet. Generate one from the last 7 days of public drops (AI summarizes themes, overlaps, tags people, and produces a Slack-ready section).
              </p>
              <button
                type="button"
                onClick={handleGenerate}
                disabled={generating}
                className="rounded-md bg-zinc-900 px-4 py-2 text-sm font-medium text-white hover:bg-zinc-800 disabled:opacity-50 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-200"
              >
                {generating ? 'Generating…' : 'Generate draft'}
              </button>
            </div>
          )}
        </section>
      )}

      <section className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
        <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-50">
          Admin access
        </h2>
        <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
          Admin users can publish the weekly digest and access digest draft controls. To grant admin access, set <code className="rounded bg-zinc-100 px-1 py-0.5 text-xs dark:bg-zinc-800">VITE_ADMIN_USER_IDS</code> in your <code className="rounded bg-zinc-100 px-1 py-0.5 text-xs dark:bg-zinc-800">.env</code> to a comma-separated list of user IDs. If unset, the default dev user is treated as admin.
        </p>
        {user && (
          <p className="mt-3 text-sm text-zinc-600 dark:text-zinc-400">
            You are currently {admin ? 'an admin' : 'not an admin'} (user: {user.id}).
          </p>
        )}
      </section>
    </div>
  )
}
