-- Mock drops for testing DesignerDrop with industrial data / Cognite AS context.
-- Run in Supabase: SQL Editor → New query → paste → Run
-- Uses placeholder image URLs so cards render; replace with real assets if needed.

-- Optional: clear existing drops (uncomment to reset before seeding)
-- TRUNCATE drops CASCADE;

INSERT INTO drops (
  id, owner_id, owner_name, owner_avatar, type, title, description,
  video_url, image_url, url, thumbnail_url, tags, mentioned_ids, project, labels, visibility, created_at, updated_at
) VALUES
(
  gen_random_uuid(),
  'user-maria',
  'Maria Chen',
  NULL,
  'screenshot',
  'Asset hierarchy explorer – new tree filters',
  'Exploration of filter chips for asset type and location. Helps users narrow the tree without losing context. Feedback from oil & gas pilot.',
  NULL,
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['assets', 'filtering', 'hierarchy', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Fusion',
  ARRAY['tree', 'filters', 'UX']::TEXT[],
  'public',
  now() - interval '2 days',
  now()
),
(
  gen_random_uuid(),
  'user-erik',
  'Erik Lindqvist',
  NULL,
  'screen_recording',
  'Work order status flow in InField',
  'Short walkthrough of status transitions (Draft → In progress → Done) and how we surface validation errors. Need to align with CDF workorders API.',
  NULL,
  NULL,
  NULL,
  'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
  ARRAY['workorders', 'InField', 'status', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'InField',
  ARRAY['workflow', 'validation']::TEXT[],
  'public',
  now() - interval '1 day',
  now()
),
(
  gen_random_uuid(),
  'user-sarah',
  'Sarah Ahmed',
  NULL,
  'screenshot',
  '3D model overlay – equipment labels',
  'Label placement and clustering for equipment in 3D. Avoiding overlap and keeping labels readable at different zoom levels.',
  NULL,
  'https://images.unsplash.com/photo-1565793298595-6a879b1d3402?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['3D', 'visualization', 'labels', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Fusion',
  ARRAY['3D', 'annotations']::TEXT[],
  'public',
  now() - interval '3 days',
  now()
),
(
  gen_random_uuid(),
  'user-james',
  'James Okonkwo',
  NULL,
  'url',
  'CDF data modeling best practices (internal doc)',
  'Shared Notion doc we use for data model reviews. Covers templates, naming, and how we map assets to CDF.',
  NULL,
  NULL,
  'https://cognite.com',
  NULL,
  ARRAY['data-model', 'CDF', 'documentation', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Data Model',
  ARRAY['documentation', 'governance']::TEXT[],
  'public',
  now() - interval '5 days',
  now()
),
(
  gen_random_uuid(),
  'user-maria',
  'Maria Chen',
  NULL,
  'screenshot',
  'Timeseries picker – date range and aggregation',
  'Redesign of the time range selector for dashboards. Supports presets (Last 24h, Last 7 days) and custom range with aggregation (avg, min, max).',
  NULL,
  'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['timeseries', 'dashboard', 'filtering', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Fusion',
  ARRAY['date-picker', 'aggregation']::TEXT[],
  'public',
  now() - interval '4 days',
  now()
),
(
  gen_random_uuid(),
  'user-erik',
  'Erik Lindqvist',
  NULL,
  'screenshot',
  'Contextualization – link assets to documents',
  'UI for linking documents to assets in Contextualization. Bulk actions and confidence indicators.',
  NULL,
  'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['contextualization', 'documents', 'assets', 'industrial']::TEXT[],
  ARRAY['user-sarah']::TEXT[],
  'Contextualization',
  ARRAY['linking', 'bulk']::TEXT[],
  'public',
  now() - interval '6 days',
  now()
),
(
  gen_random_uuid(),
  'user-sarah',
  'Sarah Ahmed',
  NULL,
  'screen_recording',
  'IoT ingestion – mapping raw signals to assets',
  'Demo of mapping pipeline config to asset hierarchy. Shows how we suggest mappings from signal naming conventions.',
  NULL,
  NULL,
  NULL,
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=300&fit=crop',
  ARRAY['IoT', 'ingestion', 'assets', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Data Model',
  ARRAY['mapping', 'pipelines']::TEXT[],
  'public',
  now() - interval '8 days',
  now()
),
(
  gen_random_uuid(),
  'user-james',
  'James Okonkwo',
  NULL,
  'screenshot',
  'Dashboard layout – responsive grid',
  'New grid system for Fusion dashboards. Breakpoints for desktop/tablet so charts reflow without breaking.',
  NULL,
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['dashboard', 'layout', 'responsive', 'Fusion']::TEXT[],
  '{}'::TEXT[],
  'Fusion',
  ARRAY['grid', 'responsive']::TEXT[],
  'public',
  now() - interval '1 day',
  now()
),
(
  gen_random_uuid(),
  'user-maria',
  'Maria Chen',
  NULL,
  'screenshot',
  'Table filtering UX – multi-select and search',
  'Combined filter bar for asset tables: search + multi-select for type/location. Aligns with table filtering patterns we use in Fusion.',
  NULL,
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['table', 'filtering', 'search', 'industrial']::TEXT[],
  ARRAY['user-erik']::TEXT[],
  'Fusion',
  ARRAY['tables', 'filters']::TEXT[],
  'public',
  now() - interval '2 days',
  now()
),
(
  gen_random_uuid(),
  'user-erik',
  'Erik Lindqvist',
  NULL,
  'url',
  'Industrial Canvas – component library (Figma)',
  'Link to Figma library for Industrial Canvas. Icons, charts, and asset tree components.',
  NULL,
  NULL,
  'https://cognite.com/products',
  NULL,
  ARRAY['design-system', 'Figma', 'Industrial Canvas', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Fusion',
  ARRAY['components', 'icons']::TEXT[],
  'public',
  now() - interval '4 days',
  now()
),
(
  gen_random_uuid(),
  'user-sarah',
  'Sarah Ahmed',
  NULL,
  'screenshot',
  'Alerts and thresholds – configuration UI',
  'Design for configuring thresholds and alert rules on timeseries. Sliders + numeric inputs, with preview of affected assets.',
  NULL,
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['alerts', 'timeseries', 'thresholds', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Fusion',
  ARRAY['alerts', 'config']::TEXT[],
  'public',
  now() - interval '7 days',
  now()
),
(
  gen_random_uuid(),
  'user-james',
  'James Okonkwo',
  NULL,
  'screenshot',
  'Onboarding – first-time Fusion setup',
  'Step-by-step flow for new tenants: connect CDF project, select template, confirm data model. Aiming to reduce time-to-first-dashboard.',
  NULL,
  'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=600&fit=crop',
  NULL,
  NULL,
  ARRAY['onboarding', 'Fusion', 'setup', 'industrial']::TEXT[],
  '{}'::TEXT[],
  'Fusion',
  ARRAY['onboarding', 'wizard']::TEXT[],
  'private',
  now() - interval '3 days',
  now()
)
ON CONFLICT DO NOTHING;

-- If you use drop_embeddings, run the weekly synthesis or create drops via the app to backfill embeddings for "Related work" and "For you".
